### ISSUE TITLE
 $ skopeo copy docker://docker.io/alpine containers-storage: Causes skopeo to segfault

### ISSUE THREAD

**Issue by rhatdan** [containers/skopeo#1174]
$ skopeo copy docker://docker.io/alpine containers-storage:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
panic(0x55f7a2d34bc0, 0xc0003cad00)
	/usr/lib/golang/src/runtime/panic.go:1064 +0x545 fp=0xc00061f6f0 sp=0xc00061f628 pc=0x55f7a2172125
runtime.goPanicIndex(0x0, 0x0)
	/usr/lib/golang/src/runtime/panic.go:88 +0xa5 fp=0xc00061f738 sp=0xc00061f6f0 pc=0x55f7a216fc65
github.com/containers/image/v5/storage.(*storageTransport).ParseReference(0x55f7a33253a0, 0x7fff77ba8929, 0x0, 0x55f7a2dd0060, 0x55f7a33253a0, 0x1, 0xc000180be0)
	/builddir/build/BUILD/skopeo-1.2.0/vendor/src/github.com/containers/image/v5/storage/storage_transport.go:227 +0x812 fp=0xc00061f978 sp=0xc00061f738 pc=0x55f7a2a3e1f2
github.com/containers/image/v5/transports/alltransports.ParseImageName(0x7fff77ba8929, 0x13, 0x55f7a2de07e0, 0xc000376f30, 0x0, 0x0)
	/builddir/build/BUILD/skopeo-1.2.0/vendor/src/github.com/containers/image/v5/transports/alltransports/alltransports.go:34 +0xdd fp=0xc00061fa08 sp=0xc00061f978 pc=0x55f7a2a4125d
main.(*copyOptions).run(0xc0001700c0, 0xc000180880, 0x2, 0x2, 0x55f7a2dbd1c0, 0xc000132008, 0x0, 0x0)
	/builddir/build/BUILD/skopeo-1.2.0/cmd/skopeo/copy.go:99 +0x305 fp=0xc00061fcd8 sp=0xc00061fa08 pc=0x55f7a2a80ba5
main.(*copyOptions).run-fm(0xc000180880, 0x2, 0x2, 0x55f7a2dbd1c0, 0xc000132008, 0x55f7a2a778e0, 0xc00061fd60)
	/builddir/build/BUILD/skopeo-1.2.0/cmd/skopeo/copy.go:79 +0x5e fp=0xc00061fd28 sp=0xc00061fcd8 pc=0x55f7a2a9483e
main.commandAction.func1(0xc00015edc0, 0xc000180880, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/skopeo-1.2.0/cmd/skopeo/utils.go:30 +0x79 fp=0xc00061fd88 sp=0xc00061fd28 pc=0x55f7a2a93cb9
github.com/spf13/cobra.(*Command).execute(0xc00015edc0, 0xc000180820, 0x2, 0x2, 0xc00015edc0, 0xc000180820)
	/builddir/build/BUILD/skopeo-1.2.0/vendor/src/github.com/spf13/cobra/command.go:842 +0x47c fp=0xc00061fe60 sp=0xc00061fd88 pc=0x55f7a2a6babc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015eb00, 0xc00001a240, 0x7fff77ba88ef, 0x1a)
	/builddir/build/BUILD/skopeo-1.2.0/vendor/src/github.com/spf13/cobra/command.go:950 +0x375 fp=0xc00061ff38 sp=0xc00061fe60 pc=0x55f7a2a6c635
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/skopeo-1.2.0/vendor/src/github.com/spf13/cobra/command.go:887
main.main()
	/builddir/build/BUILD/skopeo-1.2.0/cmd/skopeo/main.go:103 +0x85 fp=0xc00061ff88 sp=0xc00061ff38 pc=0x55f7a2a88485
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:204 +0x209 fp=0xc00061ffe0 sp=0xc00061ff88 pc=0x55f7a2174d49
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x55f7a21a7a61

goroutine 2 [force gc (idle)]:
runtime.gopark(0x55f7a2da41f0, 0x55f7a33244c0, 0x1411, 0x1)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000064fb0 sp=0xc000064f90 pc=0x55f7a2175146
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:312
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:255 +0xc5 fp=0xc000064fe0 sp=0xc000064fb0 pc=0x55f7a2174fe5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x55f7a21a7a61
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:243 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55f7a2da41f0, 0x55f7a3324700, 0x140c, 0x1)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc0000657a8 sp=0xc000065788 pc=0x55f7a2175146
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:312
runtime.bgsweep(0xc00007c000)
	/usr/lib/golang/src/runtime/mgcsweep.go:182 +0x145 fp=0xc0000657d8 sp=0xc0000657a8 pc=0x55f7a21606e5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000657e0 sp=0xc0000657d8 pc=0x55f7a21a7a61
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:217 +0x5e

goroutine 4 [sleep]:
runtime.gopark(0x55f7a2da41f0, 0x55f7a3324ea0, 0x1313, 0x2)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000065f20 sp=0xc000065f00 pc=0x55f7a2175146
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:312
runtime.scavengeSleep(0xa87ee, 0xd4f9a)
	/usr/lib/golang/src/runtime/mgcscavenge.go:241 +0xc5 fp=0xc000065f78 sp=0xc000065f20 pc=0x55f7a215e565
runtime.bgscavenge(0xc00007c000)
	/usr/lib/golang/src/runtime/mgcscavenge.go:366 +0x1ed fp=0xc000065fd8 sp=0xc000065f78 pc=0x55f7a215e78d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000065fe0 sp=0xc000065fd8 pc=0x55f7a21a7a61
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:218 +0x85

goroutine 18 [finalizer wait]:
runtime.gopark(0x55f7a2da41f0, 0x55f7a33579e8, 0xffff1410, 0x1)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000064758 sp=0xc000064738 pc=0x55f7a2175146
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:312
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:175 +0xab fp=0xc0000647e0 sp=0xc000064758 pc=0x55f7a215534b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x55f7a21a7a61
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:156 +0x66

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc000036100, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000060760 sp=0xc000060740 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc00004c000)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc0000607d8 sp=0xc000060760 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000607e0 sp=0xc0000607d8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc000036110, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000066760 sp=0xc000066740 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc00004e800)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc0000667d8 sp=0xc000066760 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000667e0 sp=0xc0000667d8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc0004d81f0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000066f60 sp=0xc000066f40 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc000051000)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc000066fd8 sp=0xc000066f60 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000066fe0 sp=0xc000066fd8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc0004d8200, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000060f60 sp=0xc000060f40 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc000053800)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc000060fd8 sp=0xc000060f60 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000060fe0 sp=0xc000060fd8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc000500000, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000061760 sp=0xc000061740 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc000056000)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc0000617d8 sp=0xc000061760 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000617e0 sp=0xc0000617d8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc0004d8210, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000508760 sp=0xc000508740 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc000058800)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc0005087d8 sp=0xc000508760 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0005087e0 sp=0xc0005087d8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc000500010, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000061f60 sp=0xc000061f40 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc00005b000)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc000061fd8 sp=0xc000061f60 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000061fe0 sp=0xc000061fd8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x55f7a2da4078, 0xc0004d8220, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:306 +0xe6 fp=0xc000504760 sp=0xc000504740 pc=0x55f7a2175146
runtime.gcBgMarkWorker(0xc00005d800)
	/usr/lib/golang/src/runtime/mgc.go:1891 +0x105 fp=0xc0005047d8 sp=0xc000504760 pc=0x55f7a2159005
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0005047e0 sp=0xc0005047d8 pc=0x55f7a21a7a61
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1839 +0x79
ERRO[0000] signal: aborted (core dumped)                
ERRO[0000] (unable to determine exit status)

**Comment by rhatdan** [comment]
$ skopeo -v
skopeo version 1.2.0

**Comment by rhatdan** [comment]
I assumed that skopeo would just use the source image name, but it should throw an error, and not crash.
