### ISSUE TITLE
skopeo doesn't take /etc/containers/registries.conf [registries.insecure] into account

### ISSUE THREAD

**Issue by TomasTomecek** [containers/skopeo#530]
We have an internal registry which is on http only and we are using skopeo to pull images from it.

Unfortunately skopeo doesn't respect the configuration in `/etc/containers/registries.conf`:
```
[registries.insecure]
registries = ['internal-url', '172.30.0.0/16']
```

```
$ atomic --debug pull --storage ostree internal-url/namespace/image:tag
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='...', profile=False, reg_type=None, src_creds=None, storage='ostree')
FATA[0000] Error determining manifest MIME type for docker://...
3439: pinging docker registry returned: Get https://...:8888/v2/: http: server gave HTTP response to HTTPS client

Traceback (most recent call last):
  File "/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.7/site-packages/Atomic/pull.py", line 62, in pull_image
    be.pull_image(self.args.image, remote_image_obj, debug=self.args.debug, assumeyes=self.args.assumeyes, src_creds=src_creds)
  File "/usr/lib/python3.7/site-packages/Atomic/backends/_ostree.py", line 113, in pull_image
    return self.syscontainers.pull_image(image, **kwargs)
  File "/usr/lib/python3.7/site-packages/Atomic/syscontainers.py", line 256, in pull_image
    self._pull_image_to_ostree(self._get_ostree_repo(), image or self.args.image, True, src_creds=src_creds)
  File "/usr/lib/python3.7/site-packages/Atomic/syscontainers.py", line 243, in _pull_image_to_ostree
    self._check_system_oci_image(repo, image, upgrade, src_creds=src_creds)
  File "/usr/lib/python3.7/site-packages/Atomic/syscontainers.py", line 2485, in _check_system_oci_image
    return self._check_system_oci_image_skopeo_copy(img, src_creds=src_creds)
  File "/usr/lib/python3.7/site-packages/Atomic/syscontainers.py", line 2491, in _check_system_oci_image_skopeo_copy
    return self._skopeo_copy_img_to_ostree(img, skopeo_img_src, src_creds=src_creds, insecure=insecure)
  File "/usr/lib/python3.7/site-packages/Atomic/syscontainers.py", line 2417, in _skopeo_copy_img_to_ostree
    util.skopeo_copy(skopeo_img_source, destination, dest_ostree_tmp_dir=temp_dir, insecure=insecure, src_creds=src_creds)
  File "/usr/lib/python3.7/site-packages/Atomic/util.py", line 454, in skopeo_copy
    return check_call(cmd, env=os.environ)
  File "/usr/lib/python3.7/site-packages/Atomic/util.py", line 214, in check_call
    return subprocess.check_call(cmd, env=env, stdin=stdin, stderr=stderr, stdout=stdout, close_fds=True)
  File "/usr/lib64/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/skopeo', 'copy', '--dest-ostree-tmp-dir', '/home/tt/.local/share/containers/atomic/.pqop3iq3', 'docker://...', 'ostree:...']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/atomic", line 201, in <module>
    sys.exit(e.returncode)
SystemExit: 1
```

Is this a bug or am I missing something? I can PM the real URLs.

The solution we found which works:
```
$ atomic --debug pull --storage ostree http:internal-url/namespace/image:tag
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='http:...', profile=False, reg_type=None, src_creds=None, storage='ostree')
Getting image source signatures
Copying blob sha256:e0f71f706c2a1ff9efee4025e27d4dfd4f328190f31d16e11ef3283bc16d6842
 71.45 MB / 71.45 MB [=====================================================] 39s
Copying blob sha256:121ab4741000471a7e2ddc687dedb440060bf9845ca415a45e99e361706f1098
 1.22 KB / 1.22 KB [========================================================] 0s
Copying blob sha256:033565e6892e5cc6dd03187d00a4575720a928db111274e0fbf31b410a093c10
 7.31 MB / 7.31 MB [=======================================================] 10s
Copying blob sha256:0e4fd875247cc80ac9ffa1d96d8de260e4dd992ec88a013fa495f89e1ee78bf0
 85.72 MB / 85.72 MB [=====================================================] 43s
Copying blob sha256:767fed3627631f4d63fbcb0b355d3aad02f91a7ea7431b5a9b1ecf06ca6b1c19
 52.68 MB / 52.68 MB [=====================================================] 22s
Copying config sha256:de59650342dadf5640a83a1fd4e099bcc752c7e800feee4f0a9e316fd67705d2
 7.99 KB / 7.99 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
```

**Comment by mtrmac** [comment]
Thanks for your report.

This is WIP in https://github.com/containers/image/pull/468 .

**Comment by TomasTomecek** [comment]
oh, neat, thank you! we'll work-around in the meanwhile then

**Comment by rhatdan** [comment]
Looks like this is fixed.
