### ISSUE TITLE
`skopeo copy` fails with `panic: d.nx != 0` when uploading to Azure ACR

### ISSUE THREAD

**Issue by mpw96** [containers/skopeo#801]
Hi,
I'm running skopeo in a docker container that was built like this:
```
FROM fedora:31
ENV SKOPEO_VERSION 0.1.40
RUN dnf install -y skopeo
```
So I'm using skopeo 1.40.

Here's my command:
```
skopeo --debug copy --src-cert-dir src/tls --dest-creds '****:****' docker://mysrcregistry/mygid/myaid:0.0.1-86.86b711b docker://mytgtregistry.azurecr.io/mygid/myaid:0.0.1-86.86b711b
```

(I changed the image name and the registry name). And here's is the end of the output:
```
...
time="2020-01-21T16:03:48Z" level=debug msg="Upload of layer sha256:dd66a6064f58eb7da569968a2f253f565732cb640b416f320e5b69fad5f16989 complete"
time="2020-01-21T16:03:48Z" level=debug msg="PUT https://mytgtregistry.azurecr.io/v2/mygid/myaid/blobs/uploads/8cdfcadc-503a-41fd-a1db-add5b00513b0?_nouploadcache=false&_state=cppxqTK2Lg23XhGyC3CgSBdj7Jn30jGtSPH9R-TQh4Z7Ik5hbWUiOiJjb20uc2FwLmhhbmEuY2xvdWQuY2xvdWRpbmZyYXN0cnVjdHVyZS9jbHVzdGVyLWxpZmVjeWNsZS1ob29rcyIsIlVVSUQiOiI4Y2RmY2FkYy01MDNhLTQxZmQtYTFkYi1hZGQ1YjAwNTEzYjAiLCJPZmZzZXQiOjQ0ODAsIlN0YXJ0ZWRBdCI6IjIwMjAtMDEtMjFUMTY6MDM6NDhaIn0%3D&digest=sha256%3A621ee864312751198307b265910ec53dcba8278e0857b31a08a21268ef366b8e"
time="2020-01-21T16:03:48Z" level=debug msg="Error uploading layer, response http.Response{Status:\"404 Not Found\", StatusCode:404, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Access-Control-Expose-Headers\":[]string{\"Docker-Content-Digest\", \"WWW-Authenticate\", \"Link\", \"X-Ms-Correlation-Request-Id\"}, \"Content-Length\":[]string{\"100\"}, \"Content-Type\":[]string{\"application/json; charset=utf-8\"}, \"Date\":[]string{\"Tue, 21 Jan 2020 16:03:48 GMT\"}, \"Docker-Distribution-Api-Version\":[]string{\"registry/2.0\"}, \"Server\":[]string{\"openresty\"}, \"Strict-Transport-Security\":[]string{\"max-age=31536000; includeSubDomains\", \"max-age=31536000; includeSubDomains\"}, \"X-Content-Type-Options\":[]string{\"nosniff\"}, \"X-Ms-Client-Request-Id\":[]string{\"\"}, \"X-Ms-Correlation-Request-Id\":[]string{\"30d6a8b6-439a-416f-8a50-f628d0d87497\"}, \"X-Ms-Request-Id\":[]string{\"896d17a4-929e-42da-bfd4-d4926b123fee\"}}, Body:(*http.bodyEOFSignal)(0xc00029ba00), ContentLength:100, TransferEncoding:[]string(nil), Close:true, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc000272700), TLS:(*tls.ConnectionState)(0xc000358790)}"
time="2020-01-21T16:03:49Z" level=debug msg="Error uploading layer, response http.Response{Status:\"404 Not Found\", StatusCode:404, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Access-Control-Expose-Headers\":[]string{\"Docker-Content-Digest\", \"WWW-Authenticate\", \"Link\", \"X-Ms-Correlation-Request-Id\"}, \"Content-Length\":[]string{\"100\"}, \"Content-Type\":[]string{\"application/json; charset=utf-8\"}, \"Date\":[]string{\"Tue, 21 Jan 2020 16:03:49 GMT\"}, \"Docker-Distribution-Api-Version\":[]string{\"registry/2.0\"}, \"Server\":[]string{\"openresty\"}, \"Strict-Transport-Security\":[]string{\"max-age=31536000; includeSubDomains\", \"max-age=31536000; includeSubDomains\"}, \"X-Content-Type-Options\":[]string{\"nosniff\"}, \"X-Ms-Client-Request-Id\":[]string{\"\"}, \"X-Ms-Correlation-Request-Id\":[]string{\"a72a197f-fcf1-492c-bbf0-590e633db62c\"}, \"X-Ms-Request-Id\":[]string{\"bcf46adf-f90a-4f3d-9ef7-507bfc339312\"}}, Body:(*http.bodyEOFSignal)(0xc000127240), ContentLength:100, TransferEncoding:[]string(nil), Close:true, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc0002a4600), TLS:(*tls.ConnectionState)(0xc000358a50)}"
time="2020-01-21T16:03:49Z" level=debug msg="PATCH https://mytgtregistry.azurecr.io/v2/mygid/myaid/blobs/uploads/cd94b159-3537-4262-8aa1-7d07ce88c541?_nouploadcache=false&_state=m4eyolUYr2le7b7ejY_3GMGzTHs4hsVQImuFJQ821XZ7Ik5hbWUiOiJjb20uc2FwLmhhbmEuY2xvdWQuY2xvdWRpbmZyYXN0cnVjdHVyZS9jbHVzdGVyLWxpZmVjeWNsZS1ob29rcyIsIlVVSUQiOiJjZDk0YjE1OS0zNTM3LTQyNjItOGFhMS03ZDA3Y2U4OGM1NDEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjAtMDEtMjFUMTY6MDM6NDkuMzg3MzgzOTJaIn0%3D"
time="2020-01-21T16:03:49Z" level=debug msg="Upload of layer sha256:ad2a0e45165f3c01f65680aa5ffba0cac4f53ae11aefff33f860470e7ad09815 complete"
panic: d.nx != 0

goroutine 176 [running]:
panic(0x561974fea4e0, 0x561975126f20)
	/usr/lib/golang/src/runtime/panic.go:722 +0x2c6 fp=0xc000622948 sp=0xc0006228b8 pc=0x5619745e28b6
crypto/sha256.(*digest).checkSum(0xc000622a68, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/sha256/sha256.go:234 +0x1db fp=0xc0006229f8 sp=0xc000622948 pc=0x5619747365fb
crypto/sha256.(*digest).Sum(0xc0002de100, 0x0, 0x0, 0x0, 0xc000622b90, 0x3598f398, 0x84cc385ed34331ac)
	/usr/lib/golang/src/crypto/sha256/sha256.go:210 +0x6b fp=0xc000622af8 sp=0xc0006229f8 pc=0x56197473624b
github.com/opencontainers/go-digest.NewDigest(0x561974cfe44b, 0x6, 0x561975152c20, 0xc0002de100, 0x101, 0xc0006230b8)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/opencontainers/go-digest/digest.go:40 +0x48 fp=0xc000622b40 sp=0xc000622af8 pc=0x5619746d95e8
github.com/opencontainers/go-digest.(*digester).Digest(0xc0005ec3e0, 0x561975151160, 0xc00014c020)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/opencontainers/go-digest/digester.go:38 +0x4b fp=0xc000622b80 sp=0xc000622b40 pc=0x5619746d9ebb
github.com/containers/image/v5/docker.(*dockerImageDestination).PutBlob(0xc000302e10, 0x561975151160, 0xc00014c020, 0x7fc6500b2290, 0xc000664600, 0xc000630690, 0x47, 0xae0c74, 0x0, 0x0, ...)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/docker/docker_image_dest.go:169 +0x6ca fp=0xc000623218 sp=0xc000622b80 pc=0x561974a6929a
github.com/containers/image/v5/copy.(*copier).copyBlobFromStream(0xc0005ae160, 0x561975151160, 0xc00014c020, 0x56197513aae0, 0xc0002b2140, 0xc000630690, 0x47, 0xae0c74, 0x0, 0x0, ...)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/copy/copy.go:1167 +0x468 fp=0xc000623778 sp=0xc000623218 pc=0x56197496ccc8
github.com/containers/image/v5/copy.(*imageCopier).copyLayerFromStream(0xc0006a0db0, 0x561975151160, 0xc00014c020, 0x56197513aae0, 0xc0002b2140, 0xc000630690, 0x47, 0xae0c74, 0x0, 0x0, ...)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/copy/copy.go:1030 +0x19a fp=0xc000623990 sp=0xc000623778 pc=0x56197496c0da
github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc0006a0db0, 0x561975151160, 0xc00014c020, 0xc000630690, 0x47, 0xae0c74, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/copy/copy.go:975 +0x375 fp=0xc000623d20 sp=0xc000623990 pc=0x56197496b575
github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x5, 0xc000630690, 0x47, 0xae0c74, 0x0, 0x0, 0x0, 0x0, 0xc0002cc580, 0x31, ...)
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/copy/copy.go:755 +0x477 fp=0xc000623f78 sp=0xc000623d20 pc=0x5619749706f7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000623f80 sp=0xc000623f78 pc=0x561974610581
created by github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2
	/builddir/build/BUILD/skopeo-be6146b0a8471b02e776134119a2c37dfb70d414/vendor/src/github.com/containers/image/v5/copy/copy.go:766 +0x1ca
```

Before the failure, some layers are uploaded successfully, the I get a 404 (check the debug output), then the panic happens. This is reproducible 100% when uploading to Azure. Something very similar works in a very stable manner when uploading to AWS ECR.

Do you have an idea what could be wrong?

T&R
Marc-Philip

**Comment by mpw96** [comment]
- There were 83 goroutines in total.
- Here is where the panic is called (line 234): https://golang.org/src/crypto/sha256/sha256.go

**Comment by mtrmac** [comment]
Thanks; this was previously reported (and is tracked) at https://github.com/containers/image/issues/750 ; I’m afraid the cause is currently unknown.
